### ISSUE TITLE
Output non wildcard domains

### ISSUE THREAD

**Issue by g33kyshivam** [theblackturtle/wildcheck#1]
Currently, there is no option to just write the non wildcard domains in a file

**Comment by g33kyshivam** [comment]
have to save the entire output into a file and cut it eg `cat wild.txt | cut -d ' ' -f3`

**Comment by theblackturtle** [comment]
You can use  `cat subdomain.txt | wildcheck -t 10 | grep 'non-wildcard' | cut -d '  ' -f3`

**Comment by theblackturtle** [comment]
Or if you just want to get non-wildcard output, you can use `cat subdomain.txt | wildcheck -t 10 | grep 'non-wildcard' > output.txt`

**Comment by g33kyshivam** [comment]
Cool, Just one more question! I just noticed it sometimes hangs even when the public dns option is true. Is it just target based?

**Comment by theblackturtle** [comment]
Maybe it takes a little time to check is your IP Address is blacklisted in that resolver or not.
